spring:

#  MySQL Config
#  datasource:
#    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
#    username: ${DB_USER}
#    password: ${DB_PASSWORD}
#
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: update

#  POSTGRES Config
#  datasource:
#    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
#    username: ${DB_USER}
#    password: ${DB_PASSWORD}
#
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: update

#  MONGO Config
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: mongodb
#      username: mongo
#      password: mongo
#      authentication-database: admin
#Note: In the pom file the dependency should be removed spring-boot-starter-data-jpa

app:
  version: v1

server:
  port: 0000